### ISSUE TITLE
Documentation: update usage 

### ISSUE THREAD

**Issue by andreslucena** [DECODEproject/dddc-credential-issuer#8]
The documentation says: 

> ## :video_game: Usage
> To start using {project_name} just (fill with real documentation)

Although we have the swagger documentation on /docs, it's necessary to have an explanation on all the flow that needs to be implemented on the frontend. Maybe we could even have some curl examples.

**Comment by puria** [comment]
Ciao @andreslucena ,

added some description on the README, it was WIP as you saw ;p

`curl` examples you already got them into swagger UI when you actually execute it, as like below 
![screenshot_2019-02-21_14-53-54](https://user-images.githubusercontent.com/10379/53173810-af39db00-35e8-11e9-8253-655c646ed41e.png)

That is the purpose of making the swagger ;)

Closing this issue, if something is missing or not clear, please open another, I'll promptly follow up.

**Comment by andreslucena** [comment]
Hi @puria 
Yes, we've seen the swagger at /docs, but we don't fully understand them yet.

I was thinking on something like this: 

---

### Example flow

First, you need to _get an Access Token_ at endpoint /token with your username and password. At the moment is hardcoded with demo / demo. 

```bash
$ curl -X POST "http://localhost/token" -H  "accept: application/json" -H  "Content-Type: application/x-www-form-urlencoded" -d "grant_type=&username=demo&password=demo&scope=&client_id=&client_secret=" 
> {"access_token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c2VybmFtZSI6ImRlbW8iLCJleHAiOjE1NTA3NjE2NTcsInN1YiI6ImFjY2VzcyJ9.GeuTbeSRTqvmEkwNR0Lp_9-mb9fLyKuhMVDXVLymR20","token_type":"bearer"}
```

Next you need to ... 

---

I don't know how to use the next endpoint, as far as I understand it should be /authorizable_attribute
