### ISSUE TITLE
Change link to PAD into a static md document to avoid unwanted edits.

### ISSUE THREAD

**Issue by uladribia** [DECODEproject/dddc-credential-issuer#9]
The title is quite self explanatory, we want to avoid unwanted edits on the PAD that describes the flow. I would instead render this into a separate markdown inside the repo, on a DOCS file.

CHeers, good job!!!!

**Comment by uladribia** [comment]
The link should be updated to map to the new pad in MD format. LInk below

https://pad.dyne.org/code/#/2/code/edit/qA7Pf4d+sQYBP2MqYgOU0isN/

**Comment by uladribia** [comment]
(Can we reopen the issue?)

**Comment by puria** [comment]
No need, already done
